<p>Our engagement was a big surprise to Valerie, at least in the "where and when" parts of it.</p>

<p>We had planned a vacation to Oahu, Hawaii with Eloise and Joe, Valerie's Mom and her husband. We arrived in Honolulu on December
24th, and made our way to our beachfront condo on Waikiki Beach. We all enjoyed the fantastic weather, especially compared to Austin
and Chicago in the winter.</p>

<p>That first night we enjoyed a fabulous sunset, and settled in looking forward to a great week of vacation fun and relaxation.</p>

<p>On Christmas Day, we all got up early, and took off in the rental car for a sight-seeing tour around the island. It turned out to
be a great day to catch the surfers on the North Shore. It was a perfecly clear and gorgeous day. After eating roadside shrimp and
coconut, we finally arrived at the beach. We set up camp and Sam asked if I would like to take walk down the beach. We found a great
private spot down the beach under a pair of palm trees and sat down. I was playing in the sand when Sam pulled a beautiful red box
from his backpack, got down on one knee and asked me to marry him! I was so surprised and so happy. We walked back and my mom asked
what we did down the beach and I said engaged! It was Christmas vacation we'll both never forget.</p>
