<p>Our story begins early in 2005, when we met through Yahoo Personals. Our
profiles matched very closely, and our love (or endurance) of the Cubs was a
icebreaker. We found out that we both enjoy many of the same things, and started
to chat frequently. </p>

<p>When we started seeing each other, we were living only a few miles apart. We
were able to see each other frequently, and we did a lot of different things
together. There was mountain biking, swimming, baseball games, hockey games,
etc. to do outside, and inside we enjoyed cooking together and movie/TV
nights.</p>

<p>One of the crazy days came during Valerie's <b>Birthday Week</b>. She got to
throw out the first pitch at a Round Rock Express game, and we got to sit in one
of the luxury boxes that night. It was called <b>Birthday Week</b> because we
celebrated her birthday for the entire week. </p>

<p>We also went to San Antonio during <b>Birthday Week</b>, one of many trips we
have enjoyed there together. For that trip we stayed at the <a
href="http://www.westinlacantera.com/">Westin La Cantera</a>, which is a great
resort. It is adjacent to Fiesta Texas, so we took the opportunity to go there
for a day as well. San Antonio has become our favorite get-away destination,
which might explain part of the reason why we are having our wedding there. It
seems like there is always something new and fun to do there, so we keep going
back.</p>

<p>One of the other great times was when Valerie's Dad flew us to Chicago for a
visit, and to see the eventual World Champion Chicago White Sox. We were treated
like royalty for that game, riding across Chicago in limousines, and enjoying
major league luxury box feast and festivities.</p>

<p>It's hard to believe that we've been engaged for over 4 months now. We have
been so busy planning the wedding, the time has just flown by. But we've been
having a lot of fun with it, and thought we would set up this site to start
celebrating a little early!<BR><BR>For those of you who haven't yet heard our
engagement story (there is probably not many of you left, as we love to tell
it!), please visit "<A href="ourengagement.asp">Our Engagement</A>" to hear how
Sam popped the question!</P>
