<p>We plan on living in Austin for the foreseeable future. We both like it here, but an adventure to a beach is always welcome.</p>

<p>We have a great house, good jobs, 2 dogs, and 2 cats. We are always busy on the weekends, enjoying outdoor activities, day trips,
or just cattin' around the city. You can find us in coffee houses, book stores, the mall, or beside the pool.</p>

<p>Valerie's family lives in Chicago, and we both love visiting the Windy City. Sam's family is in Maryland and Texas, so there is a
wide range of vacation possibilities.</p>

<p>We will try to keep everybody informed about our activities, and we appreciate all the love, friendship, and support that we
receive.</p>

<p>Lots of love and thanks,</p>

<p>Valerie and Sam</p>
